[metadata]
description-file = README.md

[nosetests]
verbosity = 2
with-coverage = true
cover-erase = true
cover-package = src
cover-html = true
cover-html-dir = coverage_report

[coverage:report]
show_missing = true
skip_covered = false
precision = 2
omit =
    tests/*
    setup.py

[flake8]
max-line-length = 88
exclude = .git,__pycache__,build,dist
ignore = E203, W503

[pylint]
disable = C0114, C0115, C0116
max-line-length = 88
output-format = colorized
